import json
from llm_handler import generate_ai_text


def build_report_prompt(file_name: str, profile: dict, chart_context: str) -> str:
    return f"""
You are a professional data analyst.

Analyze the dataset and write a business-friendly report for a non-technical audience.

Dataset name: {file_name}

Dataset profile:
{json.dumps(profile, indent=2, default=str)}

Chart context:
{chart_context}

Write the response in this exact structure:

1. Executive Summary
2. Key Insights
3. Trends and Patterns
4. Risks / Anomalies
5. Recommendations
6. Final Conclusion

Rules:
- Recommendations must be generated by AI reasoning, not rule-based.
- Use plain English.
- Be specific.
- Mention meaningful business actions.
- Avoid code.
"""


def build_recommendation_prompt(file_name: str, profile: dict, chart_context: str) -> str:
    return f"""
You are a senior business analyst.

Generate only actionable recommendations for this dataset.

Dataset name: {file_name}

Dataset profile:
{json.dumps(profile, indent=2, default=str)}

Chart context:
{chart_context}

Rules:
- Recommendations must be AI-generated.
- Do not use generic statements.
- Provide 6 to 10 recommendations.
- Each recommendation should include a reason.
- Keep the audience non-technical.
"""


def build_chat_prompt(file_name: str, profile: dict, chart_context: str, user_question: str) -> str:
    return f"""
You are an intelligent data analyst assistant.

Answer the user's question based on the dataset context below.

Dataset name: {file_name}

Dataset profile:
{json.dumps(profile, indent=2, default=str)}

Current chart context:
{chart_context}

User question:
{user_question}

Rules:
- Answer in simple business-friendly English.
- Be specific to the dataset context.
- If the question asks for insight, explain clearly.
- If exact row-level computation is not available from the provided profile, say that clearly.
- Keep the answer concise but useful.
"""


def generate_full_report(file_name: str, profile: dict, chart_context: str) -> str:
    prompt = build_report_prompt(file_name, profile, chart_context)
    return generate_ai_text(prompt)


def generate_recommendations(file_name: str, profile: dict, chart_context: str) -> str:
    prompt = build_recommendation_prompt(file_name, profile, chart_context)
    return generate_ai_text(prompt)


def generate_chat_response(file_name: str, profile: dict, chart_context: str, user_question: str) -> str:
    prompt = build_chat_prompt(file_name, profile, chart_context, user_question)
    return generate_ai_text(prompt)